module Evergreen.Migrate.V22 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V22.Types
import Evergreen.V9.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V9.Types.FrontendModel -> ModelMigration Evergreen.V22.Types.FrontendModel Evergreen.V22.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V9.Types.BackendModel -> ModelMigration Evergreen.V22.Types.BackendModel Evergreen.V22.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V9.Types.FrontendMsg -> MsgMigration Evergreen.V22.Types.FrontendMsg Evergreen.V22.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V9.Types.ToBackend -> MsgMigration Evergreen.V22.Types.ToBackend Evergreen.V22.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V9.Types.BackendMsg -> MsgMigration Evergreen.V22.Types.BackendMsg Evergreen.V22.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V9.Types.ToFrontend -> MsgMigration Evergreen.V22.Types.ToFrontend Evergreen.V22.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V9.Types.BackendModel -> Evergreen.V22.Types.BackendModel
migrate_Types_BackendModel old =
    { message = old.message
    , rooms = old.rooms |> Dict.map (\k -> migrate_Types_Room)
    , clientRooms = old.clientRooms
    , randomNext = old.randomNext
    }


migrate_Types_FrontendModel : Evergreen.V9.Types.FrontendModel -> Evergreen.V22.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Types_Route
    , mySelectedVote = old.mySelectedVote |> Maybe.map migrate_Types_Vote
    , othersVotes = old.othersVotes |> List.map migrate_Types_Vote
    , userCount = old.userCount
    , hideVotes = False
    , roomHideVotesState = False
    , roomIdInput = old.roomIdInput
    , roomId = old.roomId
    }


migrate_Types_FrontendMsg : Evergreen.V9.Types.FrontendMsg -> Evergreen.V22.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V9.Types.UrlClicked p0 ->
            Evergreen.V22.Types.UrlClicked p0

        Evergreen.V9.Types.UrlChanged p0 ->
            Evergreen.V22.Types.UrlChanged p0

        Evergreen.V9.Types.NoOpFrontendMsg ->
            Evergreen.V22.Types.NoOpFrontendMsg

        Evergreen.V9.Types.ChangedRoomIdInput p0 ->
            Evergreen.V22.Types.ChangedRoomIdInput p0

        Evergreen.V9.Types.ChangedVoteFrontendMsg p0 ->
            Evergreen.V22.Types.ChangedVoteFrontendMsg (p0 |> migrate_Types_Vote)

        Evergreen.V9.Types.StartedNewRoundFrontendMsg ->
            Evergreen.V22.Types.StartedNewRoundFrontendMsg

        Evergreen.V9.Types.JoinedRoomFrontendMsg p0 ->
            Evergreen.V22.Types.JoinedRoomFrontendMsg p0


migrate_Types_Room : Evergreen.V9.Types.Room -> Evergreen.V22.Types.Room
migrate_Types_Room old =
    { roomId = old.roomId
    , clients = old.clients
    , votes = old.votes |> List.map migrate_Types_VoteWithOwner
    , votesVisibleWhileVoting = True
    , displayVotesForThisRound = True
    }


migrate_Types_Route : Evergreen.V9.Types.Route -> Evergreen.V22.Types.Route
migrate_Types_Route old =
    case old of
        Evergreen.V9.Types.LobbyPage ->
            Evergreen.V22.Types.LobbyPage

        Evergreen.V9.Types.RoomPage p0 ->
            Evergreen.V22.Types.RoomPage p0


migrate_Types_ToBackend : Evergreen.V9.Types.ToBackend -> Evergreen.V22.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V9.Types.NoOpToBackend ->
            Evergreen.V22.Types.NoOpToBackend

        Evergreen.V9.Types.ChangedVoteToBackend p0 p1 ->
            Evergreen.V22.Types.ChangedVoteToBackend p0 (p1 |> migrate_Types_Vote)

        Evergreen.V9.Types.StartedNewRoundToBackend ->
            Evergreen.V22.Types.StartedNewRoundToBackend ""

        Evergreen.V9.Types.JoinedRoomToBackend p0 ->
            Evergreen.V22.Types.JoinedRoomToBackend p0


migrate_Types_ToFrontend : Evergreen.V9.Types.ToFrontend -> Evergreen.V22.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V9.Types.NoOpToFrontend ->
            Evergreen.V22.Types.NoOpToFrontend

        Evergreen.V9.Types.VotesUpdated p0 ->
            Evergreen.V22.Types.VotesUpdated (p0 |> List.map migrate_Types_Vote)

        Evergreen.V9.Types.UsersInRoomUpdated p0 ->
            Evergreen.V22.Types.UsersInRoomUpdated p0

        Evergreen.V9.Types.JoinedRoomWithIdToFrontend p0 p1 ->
            Evergreen.V22.Types.JoinedRoomWithIdToFrontend p0 (p1 |> List.map migrate_Types_Vote)


migrate_Types_Vote : Evergreen.V9.Types.Vote -> Evergreen.V22.Types.Vote
migrate_Types_Vote old =
    case old of
        Evergreen.V9.Types.TFB ->
            Evergreen.V22.Types.TFB

        Evergreen.V9.Types.NFC ->
            Evergreen.V22.Types.NFC

        Evergreen.V9.Types.One ->
            Evergreen.V22.Types.One


migrate_Types_VoteWithOwner : Evergreen.V9.Types.VoteWithOwner -> Evergreen.V22.Types.VoteWithOwner
migrate_Types_VoteWithOwner old =
    { client = old.client
    , vote = old.vote |> migrate_Types_Vote
    }
